#!/usr/bin/env bash
# Finesse installer: your own streaming service, set up for you.
#
#   curl -fsSL https://raw.githubusercontent.com/CoffeeCC/finesse/master/install.sh | bash
#
# Installs Docker if needed (with your OK), starts the Finesse container and
# prints the address + one-time setup code. Everything else (Jellyfin, the
# *arrs, SABnzbd, qBittorrent behind a VPN…) is set up from the browser.
#
# Options:
#   --data DIR       where movies, shows, music and downloads live
#   --root DIR       where Finesse keeps app settings      (default /opt/finesse;
#                    on a NAS, a folder on your pool or volume)
#   --port N         port for the Finesse web app            (default 8080)
#   --version V      Finesse version to install              (default latest)
#   --setup FILE     apply a setup document right away (no browser needed)
#   --yes            don't ask; accept the defaults (installs Docker if missing)
#   --plain          no colours and no pictures (also: NO_COLOR=1)
#   --uninstall      remove Finesse and the apps it installed (your files stay)
#   --help           show this
#
# Re-running is safe: an existing install is left running and its details
# are printed again.

set -euo pipefail

REPO_IMAGE="${FINESSE_IMAGE_REPO:-ghcr.io/coffeecc/finesse}"
VERSION="latest"
IMAGE=""
ROOT="/opt/finesse"
ROOT_SET=0
DATA=""
DATA_DEFAULT=""
PORT=8080
SETUP_FILE=""
YES=0
PLAIN=0
UNINSTALL=0
NAME="finesse"
NETWORK="finesse"
DOCS="https://github.com/CoffeeCC/finesse/blob/master/docs/install.md"
TRUENAS_DOCS="https://github.com/CoffeeCC/finesse/blob/master/docs/truenas.md"
TIP="0xfe70da78fd755baae45389662f3c71825dfc55f7"

# Plain until the terminal is checked (option errors print before that).
B=""; D=""; G=""; Y=""; R=""; N=""; ACC=""; HAIR=""; PINK=""
I_OK="+"; I_ERR="x"; RULE="-"
SUDO=""; LOG=""; ANIM=0

# ---------- Nessa (generated by tools/installer/art.py from the PNGs beside it; do not edit by hand) ----------
# ---------- /Nessa ----------

say()  { printf '%s\n' "$*"; }
ok()   { printf '    %s%s%s %s\n' "$G" "$I_OK" "$N" "$*"; }
warn() { printf '    %s!%s %s\n' "$Y" "$N" "$*"; }
nessa() { printf '    %sNessa ›%s %s\n' "$PINK" "$N" "$*"; }
die() {
  printf '\n    %s%s %s%s\n' "$R" "$I_ERR" "$*" "$N" >&2
  if [ -n "$LOG" ] && [ -s "$LOG" ]; then printf '    %sEverything it printed: %s%s\n' "$D" "$LOG" "$N" >&2; fi
  printf '    %sHelp: %s%s\n' "$D" "$DOCS" "$N" >&2
  nessa "Fix that and run me again. I'll pick up where we left off." >&2
  printf '\n' >&2
  exit 1
}
STEP_N=0
step() {
  STEP_N=$((STEP_N + 1))
  local title="$STEP_N · $*" rule="" n
  n=$(( 56 - ${#title} )); [ "$n" -lt 4 ] && n=4
  while [ "$n" -gt 0 ]; do rule="$rule$RULE"; n=$((n - 1)); done
  printf '\n  %s%s%s%s %s%s%s %s%s%s\n' "$ACC" "$RULE" "$RULE" "$N" "$B" "$title" "$N" "$ACC$D" "$rule" "$N"
}

# Prompts read from the terminal even when this script is piped into bash.
ask() { # ask "Question" default [hint] → echoes the answer (the hint replaces "[default]")
  local q="$1" def="${2:-}" hint="${3:-[$2]}" ans=""
  if [ "$YES" = 1 ] || [ ! -r /dev/tty ]; then echo "$def"; return; fi
  printf '    %s?%s %s%s%s %s%s%s ' "$ACC" "$N" "$B" "$q" "$N" "$D" "$hint" "$N" >/dev/tty
  read -r ans </dev/tty || true
  echo "${ans:-$def}"
}
confirm() { # confirm "Question" (default yes)
  local a
  a=$(ask "$1" "y" "(Y/n)")
  case "$a" in [nN]*) return 1 ;; *) return 0 ;; esac
}

usage() {
  if [ -r "$0" ] && head -1 "$0" | grep -q bash; then sed -n '2,/^[^#]/p' "$0" | sed '$d' | sed 's/^# \{0,1\}//'
  else say "See $DOCS"; fi
  exit 0
}

while [ $# -gt 0 ]; do
  case "$1" in
    --data) DATA="$2"; shift 2 ;;
    --root) ROOT="$2"; ROOT_SET=1; shift 2 ;;
    --port) PORT="$2"; shift 2 ;;
    --version) VERSION="${2#v}"; shift 2 ;;
    --image) IMAGE="$2"; shift 2 ;;
    --setup) SETUP_FILE="$2"; shift 2 ;;
    --yes|-y) YES=1; shift ;;
    --plain) PLAIN=1; shift ;;
    --uninstall) UNINSTALL=1; shift ;;
    --help|-h) usage ;;
    *) die "Unknown option: $1 (see --help)" ;;
  esac
done
IMAGE="${IMAGE:-$REPO_IMAGE:$VERSION}"

# ---------- the terminal ----------
# Colour on a real terminal unless NO_COLOR/--plain. Nessa only where 256 colours or more work
# (SSH rarely passes COLORTERM along, so xterm-256color is the usual case). The Linux console
# gets plain symbols: its font has no ✔.
ART=0; COLS=80
if [ -t 1 ] && [ "$PLAIN" = 0 ] && [ -z "${NO_COLOR:-}" ] && [ "${TERM:-dumb}" != dumb ]; then
  ANIM=1
  case "${COLORTERM:-}" in truecolor|24bit) ART=tc ;; esac
  if [ "$ART" = 0 ]; then case "${TERM:-}" in *256color*|*-direct|xterm-kitty|alacritty|wezterm|foot*|contour) ART=256 ;; esac; fi
  if [ "$ART" = tc ]; then
    ACC=$'\e[38;2;167;139;250m'; HAIR=$'\e[38;2;92;180;255m'; PINK=$'\e[38;2;244;114;182m'
  elif [ "$ART" = 256 ]; then
    ACC=$'\e[38;5;141m'; HAIR=$'\e[38;5;75m'; PINK=$'\e[38;5;212m'
  else
    ACC=$'\e[35m'; HAIR=$'\e[36m'; PINK=$'\e[35m'
  fi
  B=$'\e[1m'; D=$'\e[2m'; G=$'\e[32m'; Y=$'\e[33m'; R=$'\e[31m'; N=$'\e[0m'
  if [ "${TERM:-}" = linux ]; then
    ART=0; I_OK="*"
  else
    I_OK="✔"; I_ERR="✖"; RULE="─"
  fi
  c=$(stty size </dev/tty 2>/dev/null | awk '{print $2}' || true)
  case "$c" in ''|*[!0-9]*) ;; *) COLS=$c ;; esac
fi
if [ "$I_OK" = "✔" ]; then SPIN=('⠋' '⠙' '⠹' '⠸' '⠼' '⠴' '⠦' '⠧' '⠇' '⠏'); else SPIN=('|' '/' '-' '\'); fi

SPIN_PID=""
cleanup() {
  if [ -n "$SPIN_PID" ]; then kill "$SPIN_PID" 2>/dev/null || true; fi
  if [ "$ANIM" = 1 ]; then printf '\e[?25h'; fi
  return 0
}
trap cleanup EXIT
trap 'cleanup; printf "\n"; exit 130' INT TERM

# spin "Label" command… → runs it (its output goes to $LOG) with a spinner, then ✔ or ✖. Returns its status.
spin() {
  local label="$1" rc=0 i=0 t0=$SECONDS el
  shift
  [ -n "$LOG" ] || LOG=$(mktemp /tmp/finesse-install.XXXXXX)
  printf '\n--- %s\n' "$label" >>"$LOG"
  # A password prompt under a spinner gets lost, so ask for it first.
  if [ -n "$SUDO" ] && ! sudo -n true 2>/dev/null; then sudo -v </dev/tty || true; fi
  if [ "$ANIM" = 1 ]; then
    "$@" >>"$LOG" 2>&1 </dev/null &
    SPIN_PID=$!
    printf '\e[?25l'
    while kill -0 "$SPIN_PID" 2>/dev/null; do
      el=$((SECONDS - t0)); if [ "$el" -ge 3 ]; then el=" ${el}s"; else el=""; fi
      printf '\r    %s%s%s %s%s%s%s\e[K' "$ACC" "${SPIN[i % ${#SPIN[@]}]}" "$N" "$label" "$D" "$el" "$N"
      i=$((i + 1)); sleep 0.1
    done
    wait "$SPIN_PID" || rc=$?
    SPIN_PID=""
    printf '\r\e[K\e[?25h'
  else
    say "    $label…"
    "$@" >>"$LOG" 2>&1 </dev/null || rc=$?
  fi
  if [ "$rc" = 0 ]; then [ "$ANIM" = 1 ] && ok "$label"; else printf '    %s%s%s %s\n' "$R" "$I_ERR" "$N" "$label"; fi
  return "$rc"
}
# The last lines of the log, for when something failed.
log_tail() { if [ -n "$LOG" ]; then tail -n "${1:-12}" "$LOG" | sed 's/^/      /' >&2; fi; return 0; }

# draw ART line… → Nessa in half blocks (two pixels a cell), a line of text beside each row.
draw() {
  local art="$1" r x t b ti bi seq prev line top bot p ch
  shift
  local -a rows side fg bg
  side=("$@")
  IFS=$'\n' read -r -d '' -a rows <<<"$art" || true
  for ((x = 0; x < ${#NESSA_TC[@]}; x++)); do
    if [ "$ART" = tc ]; then fg[x]="38;2;${NESSA_TC[x]}"; bg[x]="48;2;${NESSA_TC[x]}"
    else fg[x]="38;5;${NESSA_256[x]}"; bg[x]="48;5;${NESSA_256[x]}"; fi
  done
  for ((r = 0; r < ${#rows[@]}; r += 2)); do
    top=${rows[r]}; bot=${rows[r + 1]:-}; line=""; prev=""
    for ((x = 0; x < ${#top}; x++)); do
      t=${top:x:1}; b=${bot:x:1}; b=${b:-.}
      p=${NESSA_ALPHA%%"$t"*}; ti=${#p}
      p=${NESSA_ALPHA%%"$b"*}; bi=${#p}
      if [ "$t" = . ] && [ "$b" = . ]; then seq="0"; ch=" "
      elif [ "$b" = . ]; then seq="0;${fg[ti]}"; ch="▀"
      elif [ "$t" = . ]; then seq="0;${fg[bi]}"; ch="▄"
      elif [ "$t" = "$b" ]; then seq="0;${fg[ti]}"; ch="█"
      else seq="0;${fg[ti]};${bg[bi]}"; ch="▀"; fi
      if [ "$seq" != "$prev" ]; then line="$line"$'\e['"${seq}m"; prev=$seq; fi
      line="$line$ch"
    done
    printf '  %s\e[0m  %s\n' "$line" "${side[r / 2]:-}"
  done
}
art_width() { local -a rows; IFS=$'\n' read -r -d '' -a rows <<<"$1" || true; echo "${#rows[0]}"; }

# "Finesse." in Nessa's colours: hair blue to violet to pink.
WORDMARK=""
letters=(F i n e s s e)
if [ "$ART" = tc ]; then cols=("92;180;255" "113;168;254" "136;154;252" "160;141;250" "190;131;232" "218;122;206" "244;114;182"); pre="1;38;2;"
elif [ "$ART" = 256 ]; then cols=(75 111 147 141 177 213 212); pre="1;38;5;"
else cols=(); fi
if [ "${#cols[@]}" -gt 0 ]; then
  for i in 0 1 2 3 4 5 6; do WORDMARK="$WORDMARK"$'\e['"${pre}${cols[i]}m${letters[i]}"; done
  WORDMARK="$WORDMARK$N$HAIR$B.$N"
else
  WORDMARK="$B${ACC}Finesse$N$HAIR.$N"
fi

# Pictures only where the terminal can show them and the installer carries them (tools/installer/art.py).
has_art() { [ "$ART" != 0 ] && [ -n "${1:-}" ]; }

banner() {
  local w=0 tag="${D}your own streaming service${N}" e="$D$PINK"
  has_art "${NESSA_HI:-}" && w=$(art_width "$NESSA_HI")
  printf '\n'
  if has_art "${NESSA_HI:-}" && [ "$COLS" -ge $((w + 32)) ]; then
    draw "$NESSA_HI" "" "$WORDMARK" "$tag" "" "" \
      "${e}╭────────────────────────╮${N}" \
      "${e}│${N} Hi! I'm Nessa.         ${e}│${N}" \
      "${e}◀${N} Let's set up your own  ${e}│${N}" \
      "${e}│${N} streaming service.     ${e}│${N}" \
      "${e}╰────────────────────────╯${N}" \
      "" "" "" "" "${D}github.com/CoffeeCC/finesse${N}"
  else
    if has_art "${NESSA_HI:-}" && [ "$COLS" -ge $((w + 4)) ]; then draw "$NESSA_HI"; printf '\n'; fi
    printf '  %s  %s\n' "$WORDMARK" "$tag"
    nessa "Hi! I'm Nessa. Let's set up your own streaming service."
  fi
}

# finale "Headline" "Sentence" → Nessa cheering, the sentence wrapped beside her (or just the two lines).
finale() {
  local w=0 head="$1" text="$2"
  local -a lines
  has_art "${NESSA_YAY:-}" && w=$(art_width "$NESSA_YAY")
  printf '\n'
  if has_art "${NESSA_YAY:-}" && [ "$COLS" -ge $((w + 26)) ]; then
    IFS=$'\n' read -r -d '' -a lines < <(printf '%s\n' "$text" | fold -s -w 22) || true
    draw "$NESSA_YAY" "" "" "" "" "" "" "$G$B$head$N" "" "${lines[@]}"
  else
    printf '  %s%s%s %s\n' "$G$B" "$head" "$N" "$text"
  fi
}

# The address between two rules: easy to spot, nothing else on its line to copy by mistake.
show_url() {
  local u="$1" rule="" n=$(( ${#1} + 6 ))
  while [ "$n" -gt 0 ]; do rule="$rule$RULE"; n=$((n - 1)); done
  printf '\n  %s%s%s\n     %s%s%s\n  %s%s%s\n' "$ACC$D" "$rule" "$N" "$B" "$u" "$N" "$ACC$D" "$rule" "$N"
}

# ---------- privileges ----------
if [ "$(id -u)" != 0 ]; then
  command -v sudo >/dev/null 2>&1 || die "Run this as root, or install sudo."
  SUDO="sudo"
fi
# By full path: sudo's PATH can leave out where some systems keep docker (Synology: /usr/local/bin).
DOCKER_BIN=$(command -v docker 2>/dev/null || echo docker)
docker_() { $SUDO "$DOCKER_BIN" "$@"; }

banner

# Ask for the password once, up front, with a reason (not mid-way under a spinner).
if [ -n "$SUDO" ] && ! sudo -n true 2>/dev/null; then
  say ""
  say "    Docker needs admin rights, so sudo will ask for your password."
  sudo -v </dev/tty 2>/dev/null || sudo -v || die "Couldn't get admin rights. Run this as a user who can use sudo."
fi

# ---------- uninstall ----------
if [ "$UNINSTALL" = 1 ]; then
  step "Removing Finesse"
  ids=$(docker_ ps -aq --filter label=finesse.managed=true || true)
  [ -n "$ids" ] && docker_ rm -f $ids >/dev/null && ok "Removed the apps Finesse installed"
  docker_ rm -f "$NAME" >/dev/null 2>&1 && ok "Removed the Finesse container" || true
  docker_ network rm "$NETWORK" >/dev/null 2>&1 || true
  say ""
  say "    Your media, downloads and app settings were NOT deleted."
  say "    They're in the folders you chose (default $ROOT). Delete them yourself if you want them gone."
  nessa "Bye for now. Come back any time."
  say ""
  exit 0
fi

# ---------- this machine ----------
step "Checking this machine"
case "$(uname -s)" in
  Linux) ;;
  Darwin) die "This installer is for Linux. Finesse doesn't run on macOS yet; a spare PC or a NAS with Linux works great." ;;
  *) die "This installer is for Linux. (On Windows, run it inside WSL: see the install guide.)" ;;
esac
# /etc/os-release is read in a subshell: it sets VERSION, which is ours.
osr() { ( . /etc/os-release 2>/dev/null; eval "printf '%s' \"\${$1:-}\"" ) || true; }
OS_ID=$(osr ID); OS_LIKE=$(osr ID_LIKE); OS_NAME=$(osr PRETTY_NAME); OS_NAME=${OS_NAME:-Linux}; OS_SHORT=$(osr NAME); OS_SHORT=${OS_SHORT:-$OS_NAME}
case "$(uname -m)" in
  x86_64|amd64) CPU="x86-64" ;;
  aarch64|arm64) CPU="ARM64" ;;
  armv6l|armv7l|armhf) die "Finesse needs a 64-bit system (this one is 32-bit $(uname -m)). On a Raspberry Pi 4 or 5, install the 64-bit Raspberry Pi OS." ;;
  *) die "Finesse needs a 64-bit x86 or ARM computer (this is $(uname -m))." ;;
esac
# A 64-bit kernel can run a 32-bit system (older Raspberry Pi OS), and Docker follows the system.
[ "$(getconf LONG_BIT 2>/dev/null || echo 64)" = 32 ] && die "This is a 32-bit system on a 64-bit computer. Finesse needs the 64-bit one (on a Raspberry Pi, the 64-bit Raspberry Pi OS)."
ok "$OS_NAME on $CPU"

# Decimal GB everywhere (like the setup wizard and disk labels), not GiB.
mem_gb=$(awk '/MemTotal/ { printf "%d", $2*1024/1e9 + 0.5 }' /proc/meminfo 2>/dev/null || echo 0)
if [ "${mem_gb:-0}" -lt 2 ]; then warn "Only ${mem_gb} GB of memory. 4 GB or more is recommended."; else ok "${mem_gb} GB memory, $(nproc 2>/dev/null || echo '?') CPU cores"; fi
# Raspberry Pi 5 kernels use 16K memory pages, which a few apps' databases don't support.
if [ "$CPU" = ARM64 ] && [ "$(getconf PAGESIZE 2>/dev/null || echo 4096)" -gt 4096 ]; then
  warn "This kernel uses 16K memory pages (Raspberry Pi 5). If an app won't start, add ${B}kernel=kernel8.img${N} to /boot/firmware/config.txt and restart."
fi

# NAS systems replace their system drive on updates (or keep it in memory), so everything
# Finesse keeps goes on a pool or volume, and Docker comes from their own app service.
NAS=""
if command -v midclt >/dev/null 2>&1 || [ -d /usr/lib/python3/dist-packages/middlewared ]; then
  NAS=truenas
  ok "TrueNAS SCALE"
  say "    ${D}To see Finesse on TrueNAS's Apps page with your other apps, install it from there instead:${N}"
  say "    ${D}$TRUENAS_DOCS${N}"
elif [ -e /etc/unraid-version ]; then
  NAS=unraid
  ok "Unraid"
  [ "$ROOT_SET" = 1 ] || ROOT=/mnt/user/appdata/finesse
  DATA_DEFAULT=/mnt/user/data
elif [ -e /etc/synoinfo.conf ] || [ -e /etc.defaults/synoinfo.conf ]; then
  NAS=synology
  ok "Synology DSM"
  vol=$(ls -d /volume[0-9]* 2>/dev/null | head -1 || true)
  if [ -n "$vol" ]; then
    [ "$ROOT_SET" = 1 ] || ROOT="$vol/docker/finesse"
    DATA_DEFAULT="$vol/data"
  fi
fi

if [ ! -e /dev/net/tun ]; then
  $SUDO modprobe tun >/dev/null 2>&1 || { [ -e /lib/modules/tun.ko ] && $SUDO insmod /lib/modules/tun.ko >/dev/null 2>&1; } || true
fi
if [ -e /dev/net/tun ]; then ok "VPN support (/dev/net/tun)"; else warn "No /dev/net/tun: Usenet works, but torrents (which need the VPN) won't be offered."; fi

WSL=0; LXC=0
if grep -qiE 'microsoft|wsl' /proc/sys/kernel/osrelease 2>/dev/null; then
  WSL=1
  warn "Windows (WSL): other devices at home reach Finesse only if WSL uses mirrored networking. See the install guide."
fi
case "$(systemd-detect-virt -c 2>/dev/null || true)" in
  lxc*) LXC=1; ok "Inside a container (LXC)" ;;
esac

# ---------- Docker ----------
step "Docker"

# How Docker gets onto this system: get.docker.com where it works, the system's own package elsewhere.
docker_plan() {
  if [ -e /run/ostree-booted ]; then echo ostree; return; fi
  case "$OS_ID" in
    ubuntu|debian|raspbian|centos|rhel|rocky|fedora) echo getdocker; return ;;
    nixos|steamos) echo "$OS_ID"; return ;;
    arch|manjaro|endeavouros|garuda|cachyos|artix) echo pacman; return ;;
    opensuse*|sles|sled) echo zypper; return ;;
    alpine) echo apk; return ;;
  esac
  case " $OS_LIKE " in
    *" ubuntu "*|*" debian "*) echo apt ;;   # Linux Mint, Pop!_OS, Zorin, elementary, Kali…
    *" arch "*) echo pacman ;;
    *suse*) echo zypper ;;
    *" rhel "*|*" centos "*) echo rhel ;;    # AlmaLinux, Oracle Linux…
    *" fedora "*) echo fedora ;;             # Nobara, Ultramarine…
    *) echo none ;;
  esac
}
inst_getdocker() { curl -fsSL https://get.docker.com | $SUDO sh; }
inst_apt()    { $SUDO apt-get update -q && $SUDO env DEBIAN_FRONTEND=noninteractive apt-get install -y -q docker.io; }
inst_fedora() { $SUDO dnf install -y moby-engine; }
inst_rhel()   { $SUDO dnf install -y dnf-plugins-core && $SUDO dnf config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo && $SUDO dnf install -y docker-ce docker-ce-cli containerd.io; }
inst_pacman() { $SUDO pacman -S --noconfirm --needed docker; }
inst_zypper() { $SUDO zypper --non-interactive install docker; }
inst_apk()    { $SUDO apk add docker && $SUDO rc-update add docker default; }

install_docker() {
  local plan how
  case "$NAS" in
    unraid) die "Docker is off. Turn it on in Unraid (Settings → Docker → Enable Docker), then run this again." ;;
    synology) die "Docker isn't installed. Install Container Manager from the Package Center, then run this again." ;;
  esac
  plan=$(docker_plan)
  say "    Finesse runs every app in Docker, which isn't installed yet."
  case "$plan" in
    ostree)
      # Bazzite, Bluefin, Aurora, Fedora Silverblue/Kinoite…: packages are layered onto the system, then a restart.
      say "    $OS_SHORT is an image-based system, so Docker is added as a layer and needs one restart."
      confirm "Add Docker now (rpm-ostree install moby-engine)?" || die "Add Docker yourself (sudo rpm-ostree install moby-engine), restart, and run this again."
      spin "Adding Docker to the system (a few minutes)" $SUDO rpm-ostree install --idempotent moby-engine \
        || { log_tail; die "Docker couldn't be added. Try it yourself: sudo rpm-ostree install moby-engine"; }
      finale "Docker is in." "One restart to go: restart the computer, then run the same install command again. It picks up from here."
      say ""
      if [ "$YES" = 0 ] && [ -r /dev/tty ]; then
        case "$(ask "Restart now?" "n" "(y/N)")" in [yY]*) $SUDO systemctl reboot ;; esac
      fi
      exit 0
      ;;
    nixos)
      die "On NixOS, add ${B}virtualisation.docker.enable = true;${N} to /etc/nixos/configuration.nix, run sudo nixos-rebuild switch, then run this again." ;;
    steamos)
      die "SteamOS's system is read-only and resets on updates, so Docker can't be installed on it. Use a regular Linux (or Bazzite) for your server." ;;
    none)
      die "This installer doesn't know how to install Docker on $OS_SHORT. Install it (docs.docker.com/engine/install), then run this again." ;;
    getdocker) how="from get.docker.com"; command -v curl >/dev/null 2>&1 || die "curl is needed to install Docker. Install curl, then run this again." ;;
    apt) how="the docker.io package" ;;
    fedora) how="the moby-engine package" ;;
    rhel) how="from Docker's repository" ;;
    *) how="with $plan" ;;
  esac
  confirm "Install Docker now ($how)?" || die "Install Docker (docs.docker.com/engine/install), then run this again."
  nessa "This is the slow part. Good time for a drink."
  spin "Installing Docker (a minute or two)" "inst_$plan" \
    || { log_tail; die "Docker didn't install (the last lines are above). Install it yourself (docs.docker.com/engine/install) and run this again."; }
}

start_docker() {
  $SUDO systemctl enable --now docker || $SUDO service docker start || $SUDO rc-service docker start || true
  for _ in 1 2 3 4 5 6 7 8 9 10; do docker_ info >/dev/null 2>&1 && return 0; sleep 1; done
  return 1
}

DOCKER_BIN=$(command -v docker 2>/dev/null || true)
if [ -n "$DOCKER_BIN" ]; then
  case "$DOCKER_BIN" in
    /snap/*) die "This Docker comes from the Snap Store, which can't reach folders like $ROOT. Switch to the regular Docker: run sudo snap remove docker, then this again (it installs Docker for you)." ;;
  esac
  if "$DOCKER_BIN" --version 2>&1 | grep -qi podman; then
    if [ -e /run/ostree-booted ]; then fix="sudo rpm-ostree override remove podman-docker --install moby-engine, then restart"
    else fix="sudo dnf swap podman-docker moby-engine"; fi
    die "This computer's docker command is Podman. Finesse needs Docker itself: run $fix, and run this again."
  fi
fi
if [ "$NAS" = truenas ] && ! docker_ info >/dev/null 2>&1; then
  die "Docker isn't running yet. In TrueNAS, open Apps and choose a pool for apps (Apps → Configuration → Choose Pool), then run this again."
fi
if [ -z "$DOCKER_BIN" ]; then
  install_docker
  DOCKER_BIN=$(command -v docker 2>/dev/null || echo /usr/bin/docker)
fi
if ! docker_ info >/dev/null 2>&1; then
  if ! spin "Starting Docker" start_docker; then
    log_tail 6
    if [ "$LXC" = 1 ]; then die "Docker can't start inside this container. In Proxmox, turn on Nesting (and keyctl) under the container's Options → Features, restart it, and run this again."
    elif [ "$WSL" = 1 ] && [ ! -d /run/systemd/system ]; then die "Docker can't start because WSL isn't running systemd. Add [boot] systemd=true to /etc/wsl.conf, run wsl --shutdown in Windows, and run this again (or use Docker Desktop's WSL integration)."
    else die "Docker is installed but won't start. Look at: sudo journalctl -u docker -n 30"; fi
  fi
fi
ok "Docker $(docker_ version --format '{{.Server.Version}}' 2>/dev/null || true)"
# Fedora, Bazzite, RHEL…: SELinux keeps containers out of their folders unless told otherwise.
SECOPT=""
if docker_ info --format '{{json .SecurityOptions}}' 2>/dev/null | grep -q selinux; then
  SECOPT="--security-opt label=disable"
  ok "SELinux is on; Finesse's apps will be allowed into their folders"
fi

# ---------- already installed? ----------
existing=$(docker_ ps -a --filter "name=^/${NAME}$" --format '{{.Status}}' || true)
if [ -n "$existing" ]; then
  step "Finesse is already installed"
  case "$existing" in Up*) ok "Running ($existing)" ;; *) docker_ start "$NAME" >/dev/null && ok "Started it again" ;; esac
  PORT=$(docker_ port "$NAME" 8080/tcp 2>/dev/null | head -1 | sed 's/.*://' || echo "$PORT")
  PORT=${PORT:-8080}
  say "    ${D}Updates happen from inside Finesse (Settings → Updates). To start over, run the installer with --uninstall.${N}"
else
  # ---------- folders ----------
  step "Where things go"
  if [ "$NAS" = truenas ] && [ "$ROOT_SET" = 0 ]; then
    pool=$(ls -d /mnt/*/ 2>/dev/null | grep -v -e '/mnt/\.' -e 'ix-apps' | head -1 || true)
    [ -n "$pool" ] || die "No pool found under /mnt. Create one in TrueNAS (Storage), then run this again."
    ROOT=$(ask "Settings folder (on a pool)" "${pool%/}/finesse")
  fi
  if [ -z "$DATA" ]; then
    say "    Movies, shows, music and downloads need space. Disks with the most room:"
    df -P -k -x tmpfs -x devtmpfs -x overlay -x squashfs -x efivarfs 2>/dev/null | awk 'NR>1 { printf "%d GB free  %s\n", $4*1024/1e9, $6 }' | sort -rn | head -4 | sed "s|^|      $D|; s|\$|$N|" || true
    DATA=$(ask "Media & downloads folder" "${DATA_DEFAULT:-$ROOT/data}")
  fi
  ROOT="${ROOT%/}"; DATA="${DATA%/}"
  case "$ROOT$DATA" in *" "*) die "Please use folder paths without spaces." ;; esac
  case "$NAS" in
    truenas|unraid)
      for d in "$ROOT" "$DATA"; do
        case "$d" in /mnt/?*) ;; *) die "On a NAS, keep Finesse's folders on a pool (under /mnt/), not $d: system updates replace everything else." ;; esac
      done ;;
    synology)
      for d in "$ROOT" "$DATA"; do
        case "$d" in /volume[0-9]*/?*) ;; *) die "On Synology, keep Finesse's folders on a volume (under /volume1/ or similar), not $d." ;; esac
      done ;;
  esac
  $SUDO mkdir -p "$ROOT/config" "$DATA" || die "Couldn't create $ROOT or $DATA"
  free_gb=$(df -P -k "$DATA" | awk 'NR==2 { printf "%d", $4*1024/1e9 }')
  ok "Settings in $ROOT"
  ok "Media in $DATA (${free_gb} GB free)"
  [ "${free_gb:-0}" -lt 50 ] && warn "That's not much room. A single 4K movie can be 50 GB."

  # The apps run as this user so your files stay yours.
  if [ -n "${SUDO_USER:-}" ] && [ "$SUDO_USER" != root ]; then
    PUID=$(id -u "$SUDO_USER"); PGID=$(id -g "$SUDO_USER")
  elif [ "$(id -u)" != 0 ]; then
    PUID=$(id -u); PGID=$(id -g)
  elif [ "$NAS" = truenas ]; then
    PUID=568; PGID=568   # TrueNAS's "apps" user, like its own apps
  elif [ "$NAS" = unraid ]; then
    PUID=99; PGID=100    # Unraid's nobody:users, like its own apps
  else
    PUID=1000; PGID=1000
  fi
  $SUDO chown "$PUID:$PGID" "$ROOT/config" "$DATA" 2>/dev/null || true

  TZ_NAME=$(timedatectl show -p Timezone --value 2>/dev/null || cat /etc/timezone 2>/dev/null || readlink /etc/localtime 2>/dev/null | sed 's|.*/zoneinfo/||' || true)
  TZ_NAME=${TZ_NAME:-UTC}

  # ---------- port ----------
  port_busy() { (command -v ss >/dev/null 2>&1 && ss -ltn "( sport = :$1 )" | grep -q ":$1 ") || (echo >/dev/tcp/127.0.0.1/"$1") 2>/dev/null; }
  want=$PORT
  while port_busy "$PORT"; do PORT=$((PORT + 1)); [ "$PORT" -gt $((want + 20)) ] && die "Ports $want–$PORT are all in use. Pick one with --port."; done
  [ "$PORT" != "$want" ] && warn "Port $want is in use, so Finesse will use $PORT."

  # ---------- start ----------
  step "Starting Finesse"
  if ! spin "Downloading Finesse" docker_ pull "$IMAGE"; then
    [ -n "$(docker_ images -q "$IMAGE")" ] || { log_tail 4; die "Couldn't download $IMAGE. Check the internet connection (and the version, if you gave one)."; }
    warn "Using the copy already on this machine"
  fi
  docker_ network inspect "$NETWORK" >/dev/null 2>&1 || docker_ network create "$NETWORK" --label finesse.managed=true >/dev/null
  # SECOPT is two words or none, so it's left unquoted.
  docker_ run -d --name "$NAME" \
    --restart unless-stopped \
    --network "$NETWORK" --network-alias finesse \
    -p "$PORT:8080" $SECOPT \
    -v /var/run/docker.sock:/var/run/docker.sock \
    -v "$ROOT:$ROOT" -v "$DATA:$DATA" \
    -e FINESSE_ROOT="$ROOT" -e FINESSE_DATA="$DATA" -e FINESSE_CONFIG_DIR="$ROOT/config/finesse" \
    -e PUID="$PUID" -e PGID="$PGID" -e TZ="$TZ_NAME" \
    "$IMAGE" >/dev/null || die "Docker couldn't start Finesse."
  ok "Started on port $PORT"
fi

# ---------- wait until it answers ----------
health() {
  if command -v curl >/dev/null 2>&1; then curl -fsS "http://127.0.0.1:$PORT/api/health" >/dev/null 2>&1
  else wget -q -O /dev/null "http://127.0.0.1:$PORT/api/health" 2>/dev/null; fi
}
wait_health() { for _ in $(seq 1 90); do health && return 0; sleep 1; done; return 1; }
health || spin "Waiting for Finesse to wake up" wait_health || die "Finesse didn't answer on port $PORT. See: sudo docker logs $NAME"

# Firewalls that turn other devices away by default (Fedora Server, RHEL…): let the web app through.
if command -v firewall-cmd >/dev/null 2>&1 && systemctl is-active --quiet firewalld 2>/dev/null; then
  if ! $SUDO firewall-cmd --query-port="$PORT/tcp" >/dev/null 2>&1; then
    if $SUDO firewall-cmd --permanent --add-port="$PORT/tcp" >/dev/null 2>&1 && $SUDO firewall-cmd --reload >/dev/null 2>&1; then ok "Let port $PORT through the firewall"
    else warn "Couldn't open port $PORT in the firewall. Run: sudo firewall-cmd --permanent --add-port=$PORT/tcp && sudo firewall-cmd --reload"; fi
  fi
fi

# The address people at home reach this machine on: the one the default route
# leaves from, unless that's a VPN; else the first real network card's.
# (`hostname -I` lists Docker bridges and Tailscale too, in no useful order.)
virtual_if='^(docker|br-|veth|virbr|cni|flannel|cali|tailscale|tun|tap|wg|zt|lo)'
IP=""
route_dev=$(ip route get 1.1.1.1 2>/dev/null | awk '{for (i=1;i<NF;i++) if ($i=="dev") print $(i+1)}' || true)
if [ -n "$route_dev" ] && ! printf '%s' "$route_dev" | grep -Eq "$virtual_if"; then
  IP=$(ip route get 1.1.1.1 2>/dev/null | awk '{for (i=1;i<NF;i++) if ($i=="src") print $(i+1)}' || true)
fi
[ -n "$IP" ] || IP=$(ip -4 -o addr show scope global 2>/dev/null | awk '{print $2, $4}' | grep -Ev "$virtual_if" | head -1 | awk '{sub("/.*","",$2); print $2}' || true)
[ -n "$IP" ] || IP=$(hostname -I 2>/dev/null | awk '{print $1}' || true)
IP=${IP:-localhost}
URL="http://$IP:$PORT"

# ---------- headless setup ----------
if [ -n "$SETUP_FILE" ]; then
  [ -r "$SETUP_FILE" ] || die "Can't read $SETUP_FILE"
  step "Applying $SETUP_FILE"
  docker_ exec -i "$NAME" finesse setup apply - <"$SETUP_FILE" || die "Setup stopped. Fix the problem above and run: sudo docker exec -i $NAME finesse setup apply - < $SETUP_FILE"
  finale "Your server is ready." "Open it on any phone, TV or computer at home and sign in."
  show_url "$URL"
  say ""
  exit 0
fi

CODE=$(docker_ exec "$NAME" finesse setup-code 2>/dev/null || true)
if [ -n "$CODE" ]; then
  finale "All set!" "Finesse is running. Open the link below on any phone or computer at home to finish setting up."
  show_url "$URL/finesse/setup?code=$CODE"
  say "    Setup code ${B}$CODE${N}   ${D}show it again: sudo docker exec $NAME finesse setup-code${N}"
  if command -v qrencode >/dev/null 2>&1; then say ""; qrencode -t ANSIUTF8 -m 2 "$URL/finesse/setup?code=$CODE" | sed 's/^/  /'; fi
else
  finale "Finesse is running." "Open it on any phone, TV or computer at home."
  show_url "$URL"
fi
say ""
say "    ${D}Health check any time: sudo docker exec $NAME finesse doctor${N}"
say "    ${D}Finesse is free. Tips welcome (ETH): $TIP${N}"
say ""
if [ -n "$LOG" ]; then rm -f "$LOG"; fi
exit 0
