"""Nessa for the installer: turns nessa-hi.png and nessa-yay.png into the palette rows install.sh draws with
half blocks (two pixels per terminal cell). Rewrites the block between the NESSA markers in install.sh.

  python3 tools/installer/art.py        (needs Pillow)

Each row is one character per pixel: '.' is see-through, anything else indexes the palette. The palette is written
twice, as 24-bit colours and as the nearest xterm-256 colours (SSH rarely passes COLORTERM along, so most remote
terminals get the 256 version)."""
import os, re
from PIL import Image

HERE = os.path.dirname(os.path.abspath(__file__))
INSTALL = os.path.join(HERE, '..', '..', 'install.sh')
ALPHA = '0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ'
ARTS = [('NESSA_HI', 'nessa-hi.png'), ('NESSA_YAY', 'nessa-yay.png')]


def xterm256():
    steps = [0, 95, 135, 175, 215, 255]
    cube = [(16 + 36 * r + 6 * g + b, (steps[r], steps[g], steps[b])) for r in range(6) for g in range(6) for b in range(6)]
    grey = [(232 + i, (8 + 10 * i,) * 3) for i in range(24)]
    return cube + grey   # 0-15 left out: terminal themes change them


def lab(rgb):
    """sRGB → CIELAB, so "nearest" means nearest to the eye (plain RGB distance turns navy teal)."""
    def lin(c):
        c /= 255
        return c / 12.92 if c <= 0.04045 else ((c + 0.055) / 1.055) ** 2.4
    r, g, b = (lin(c) for c in rgb)
    x, y, z = (r * 0.4124 + g * 0.3576 + b * 0.1805) / 0.95047, r * 0.2126 + g * 0.7152 + b * 0.0722, (r * 0.0193 + g * 0.1192 + b * 0.9505) / 1.08883
    f = lambda t: t ** (1 / 3) if t > 0.008856 else 7.787 * t + 16 / 116
    return 116 * f(y) - 16, 500 * (f(x) - f(y)), 200 * (f(y) - f(z))


def nearest(rgb, table):
    want = lab(rgb)
    return min(table, key=lambda e: sum((a - b) ** 2 for a, b in zip(want, lab(e[1]))))[0]


images = [(name, Image.open(os.path.join(HERE, f)).convert('RGBA')) for name, f in ARTS]
colours = sorted({p[:3] for _, im in images for p in im.getdata() if p[3] > 127})
assert len(colours) <= len(ALPHA), f'{len(colours)} colours; the alphabet has {len(ALPHA)}'
index = {c: ALPHA[i] for i, c in enumerate(colours)}
table = xterm256()

out = ['# ---------- Nessa (generated by tools/installer/art.py from the PNGs beside it; do not edit by hand) ----------',
       'NESSA_ALPHA=' + ALPHA[:len(colours)],
       'NESSA_TC=(' + ' '.join('"%d;%d;%d"' % c for c in colours) + ')',
       'NESSA_256=(' + ' '.join(str(nearest(c, table)) for c in colours) + ')']
for name, im in images:
    w, h = im.size
    rows = [''.join(index[im.getpixel((x, y))[:3]] if im.getpixel((x, y))[3] > 127 else '.' for x in range(w)) for y in range(h)]
    if len(rows) % 2: rows.append('.' * w)
    out.append(f"{name}='\n" + '\n'.join(rows) + "'")
block = '\n'.join(out) + '\n# ---------- /Nessa ----------'

src = open(INSTALL).read()
new, n = re.subn(r'# ---------- Nessa \(generated.*?# ---------- /Nessa ----------', lambda _: block, src, flags=re.S)
assert n == 1, 'install.sh needs the NESSA markers'
open(INSTALL, 'w').write(new)
print(f'{len(colours)} colours, {", ".join(f"{n} {im.size[0]}x{im.size[1]}" for n, im in images)}')
